/*
CREATE TABLE PELICULA(
ID_PELICULA INTEGER PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(120),
SINOPSIS VARCHAR(500) 
);
*/

CREATE TABLE CLIENTE (ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT, NOMBRE VARCHAR(120), SUELDO FLOAT);
CREATE TABLE DIRECCION (ID_DIRECCION INTEGER PRIMARY KEY AUTO_INCREMENT,ID_CLIENTE INTEGER, COLONIA VARCHAR(300), CALLE VARCHAR(300),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));

